title: Gothic Linux Guide
remote_theme: pmarsceill/just-the-docs
nav:
  - title: "Home"
    url: index.md
  - title: "Installation"
    children:
      - title: "Gothic I/II"
        url: gothic-install.md
theme:
  color: "blue"
header:
  show: true
