title: Gothic Linux Guide
description: A guide to running Gothic on Linux
remote_theme: just-the-docs/just-the-docs

url: https://yorick0499.github.io
baseurl: /gothic-linux-guide/en/index.md

search-enabled: true

aux_links:
  "EN ğŸ‡¬ğŸ‡§":
    - "/en/index.md"
  "PL ğŸ‡µğŸ‡±":
    - "/pl/index.md"

aux_links_new_tab: false
